### ISSUE TITLE
Rather than wrapping each endpoint on the agent middleware, is it possible to do the global mux.Use() wrapper

### ISSUE THREAD

**Issue by tim-mwangi** [hypertrace/goagent#58]
Also, what about all the routes being declared with HandleFunc rather than Handler? Is it possible to work with HandleFunc rather than Handle?

**Comment by tim-mwangi** [comment]
@jcchavezs had this quick comment on this.

> I think it is totally possible but it has some difficulties. For example, tweaking the name of the span will be hard as it has limited access to the request elements (mostly method and url) whereas wrapping per endpoint allows to have better naming unless one does something like last piece of https://medium.com/devthoughts/instrumenting-a-go-application-with-zipkin-b79cc858ac3e.

**Comment by jcchavezs** [comment]
Closed by https://github.com/hypertrace/goagent/pull/59
